# -*- coding: utf-8 -*-
"""Breast_Cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bPwLgdI7HNNTywQtiWh91GxMGm0eIaFA

## Project Setup: Install Libraries, Mount Google Drive, and Download Dataset
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

"""Now, we will set up the Kaggle API to download the Breast Cancer Mammograms dataset. You'll need to upload your kaggle.json file (containing your API credentials) to your Colab environment.

Instructions to get your kaggle.json:

Go to Kaggle
Click on your profile picture in the top right corner and select 'My Account'.
Scroll down to the 'API' section and click 'Create New API Token'. This will download kaggle.json to your computer.
Once you have the kaggle.json file, run the following cell and upload it when prompted.
"""

# Upload kaggle.json for API authentication
from google.colab import files
import os

# Create a .kaggle directory if it doesn't exist
if not os.path.exists('/root/.kaggle'):
    os.makedirs('/root/.kaggle')

# Upload kaggle.json file
print("Please upload your kaggle.json file:")
files.upload()

# Move kaggle.json to the appropriate directory
!mv kaggle.json /root/.kaggle/
!chmod 600 /root/.kaggle/kaggle.json

"""With the Kaggle API configured, we can now download the specified dataset. The dataset will be downloaded to a directory named breast-cancer-mammograms."""

# import os

# # --- Project Constants (re-defining for clarity and potential modification) ---
# BASE_DIR = '/content/drive/MyDrive/Mammography_Denoising_Project' # Base directory in Google Drive

# # Download the dataset from Kaggle
# !kaggle datasets download -d eoussama/breast-cancer-mammograms

# # Define the target directory for unzipping, consistent with BASE_DIR
# target_unzip_dir = os.path.join(BASE_DIR, 'input_dataset')

# # Create Athe target directory if it doesn't exist
# os.makedirs(target_unzip_dir, exist_ok=True)

# # Unzip the dataset to the specified directory
# !unzip breast-cancer-mammograms.zip -d {target_unzip_dir}

# print(f"Dataset downloaded and unzipped to '{target_unzip_dir}'.")

# Download the dataset from Kaggle
!kaggle datasets download -d eoussama/breast-cancer-mammograms

# Unzip the dataset
!unzip breast-cancer-mammograms.zip -d input_dataset

print("Dataset downloaded and unzipped to 'input_dataset/'.")

"""## Define Project Constants and Utility Functions

This section defines various constants and utility functions essential for the project's operation. This includes setting up base directories, defining image processing parameters, and creating a function to ensure all required output folders exist.
"""

import os
import cv2
import numpy as np
import pandas as pd
from skimage.metrics import mean_squared_error, peak_signal_noise_ratio, structural_similarity
from skimage.util import random_noise
from skimage.restoration import wiener # Only import Wiener filter from scikit-image
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter as gf_ndimage, uniform_filter # Added uniform_filter


# --- Custom Anscombe Transform Functions ---
def anscombe(image, constant=3/8):
    """Applies the Anscombe transform for variance stabilization of Poisson data."""
    # Ensure image is float to avoid precision issues
    image_float = image.astype(np.float64)
    return 2.0 * np.sqrt(image_float + constant)

def inverse_anscombe(transformed_image, constant=3/8):
    """Applies the inverse Anscombe transform."""
    # Ensure image is float
    transformed_image_float = transformed_image.astype(np.float64)
    # Clip to avoid issues with negative values from (transformed_image_float/2)**2 - constant
    # Especially relevant if input image had zero values which become 2*sqrt(constant) after transform
    return np.maximum(0.0, (transformed_image_float / 2.0)**2 - constant)


# --- Project Constants (re-defining for clarity and potential modification) ---
BASE_DIR = '/content/Mammography_Denoising_Project' # Base directory in Google Drive

INPUT_DATASET_DIR = '/content/input_dataset' # Dataset downloaded from Kaggle

IMAGE_SIZE = (256, 256)

# Output directories
OUTPUT_DIR = os.path.join(BASE_DIR, 'output')
NOISY_DIR = os.path.join(OUTPUT_DIR, 'noisy')
DENOISED_DIR = os.path.join(OUTPUT_DIR, 'denoised')
RESULTS_DIR = os.path.join(OUTPUT_DIR, 'results')

# Supported image formats
SUPPORTED_FORMATS = ('.png', '.jpg', '.jpeg', '.tif', '.tiff', '.bmp')

# --- Noise Type Functions ---
def add_mixed_poisson_gaussian_noise(img, gaussian_var=0.01):
    """Applies Poisson noise followed by Gaussian noise."""
    poisson_noisy_img = random_noise(img, mode='poisson')
    mixed_noisy_img = random_noise(poisson_noisy_img, mode='gaussian', var=gaussian_var)
    return mixed_noisy_img

# Noise types and their application functions
NOISE_TYPES = {
    'gaussian': lambda img: random_noise(img, mode='gaussian', var=0.01),
    's&p': lambda img: random_noise(img, mode='s&p', amount=0.05),
    'speckle': lambda img: random_noise(img, mode='speckle', var=0.04),
    'poisson': lambda img: random_noise(img, mode='poisson'),
    'mixed_poisson_gaussian': lambda img: add_mixed_poisson_gaussian_noise(img)
}

# --- Denoising Methods Functions ---
def wiener_filter(img):
    """Applies a Wiener filter using scikit-image's implementation.
    For simplicity, psf (point spread function) can be left None for a non-blind deconvolution.
    """
    dummy_psf = gf_ndimage(np.zeros((3,3)), 1, output=None, mode='constant')
    dummy_psf[1,1] = 1 # make a point spread function for deblurring example
    # Normalise it
    dummy_psf /= dummy_psf.sum()

    # Apply Wiener filter. The `balance` parameter (default 0.5) balances inverse filtering with noise smoothing.
    # For pure denoising, a lower `balance` value might be more appropriate if we don't have strong blurring.
    denoised_img = wiener(img, dummy_psf, balance=0.1) # Adjusted balance for more noise reduction emphasis
    return denoised_img

def anscombe_wiener_denoising(img):
    """Applies Anscombe transform, then Wiener filter, then inverse Anscombe transform."""
    transformed_img = anscombe(img) # Use custom anscombe

    # Use the existing wiener_filter function
    denoised_transformed_img = wiener_filter(transformed_img)

    denoised_img = inverse_anscombe(denoised_transformed_img) # Use custom inverse_anscombe
    return np.clip(denoised_img, 0, 1)

def adaptive_median_filter(img, s_max=7):
    """
    Applies an adaptive median filter.
    s_max: maximum window size.
    """
    img_uint8 = (img * 255).astype(np.uint8)
    H, W = img_uint8.shape
    out = np.copy(img_uint8)

    for i in range(H):
        for j in range(W):
            s = 3 # initial window size
            while s <= s_max:
                half_s = s // 2
                r_min, r_max = max(0, i - half_s), min(H, i + half_s + 1)
                c_min, c_max = max(0, j - half_s), min(W, j + half_s + 1)
                window = img_uint8[r_min:r_max, c_min:c_max]

                if window.size == 0:
                    s += 2
                    continue

                med = np.median(window)
                z_min = np.min(window)
                z_max = np.max(window)

                pixel_val = img_uint8[i, j]

                if z_min < med < z_max: # If median is not an impulse
                    if z_min < pixel_val < z_max: # If pixel is not an impulse
                        out[i, j] = pixel_val
                    else: # Pixel is an impulse
                        out[i, j] = med
                    break
                else: # Median is an impulse, increase window size
                    s += 2
                    if s > s_max: # Max window size reached, use median
                        out[i, j] = med
                        break
    return out.astype(np.float64) / 255.0

def kuan_filter(img, win_size=5, noise_var_estimate=0.04):
    """
    Applies the Kuan filter for speckle noise reduction.
    img: float64 [0,1] image.
    win_size: window size for local statistics.
    noise_var_estimate: estimated variance of the speckle noise (e.g., from NOISE_TYPES['speckle'] var).
    """
    local_mean = uniform_filter(img, size=win_size)
    local_sq_mean = uniform_filter(img**2, size=win_size)
    local_variance = local_sq_mean - local_mean**2

    # Clamp local_variance to avoid division by zero
    local_variance[local_variance < 1e-6] = 1e-6

    # Kuan filter coefficient (B)
    B = 1 - (noise_var_estimate / local_variance)
    B[B < 0] = 0 # Clamp B to be non-negative

    denoised_img = local_mean + B * (img - local_mean)
    return np.clip(denoised_img, 0, 1)

# Denoising methods and their application functions
# Note: OpenCV functions typically expect uint8 images and return uint8.
# We will convert back to float64 [0,1] for consistency with scikit-image metrics.
DENOISING_METHODS = {
    'median': lambda img: cv2.medianBlur((img * 255).astype(np.uint8), 5).astype(np.float64) / 255.0,
    'gaussian': lambda img: cv2.GaussianBlur((img * 255).astype(np.uint8), (5, 5), 0).astype(np.float64) / 255.0,
    'wiener': lambda img: wiener_filter(img), # Custom Wiener filter
    'bilateral': lambda img: cv2.bilateralFilter((img * 255).astype(np.uint8), 9, 75, 75).astype(np.float64) / 255.0,
    'non_local_means': lambda img: cv2.fastNlMeansDenoising((img * 255).astype(np.uint8), 10, 7, 21).astype(np.float64) / 255.0,
    'anscombe_wiener': lambda img: anscombe_wiener_denoising(img),
    'adaptive_median': lambda img: adaptive_median_filter(img),
    # 'kuan': lambda img: kuan_filter(img)
}

# --- Utility Functions ---
def create_directories(dirs):
    """Creates directories if they do not exist."""
    for dir_path in dirs:
        os.makedirs(dir_path, exist_ok=True)
        print(f"Ensured directory exists: {dir_path}")

# Create all necessary project directories (redundant if already run, but ensures existence)
create_directories([OUTPUT_DIR, NOISY_DIR, DENOISED_DIR, RESULTS_DIR])

print("Project constants and utility functions (including refined Wiener filter) defined, and directories ensured.")

import os
import cv2
import numpy as np
import pandas as pd
from skimage.metrics import mean_squared_error, peak_signal_noise_ratio, structural_similarity

# Note: IMAGE_SIZE is assumed to be defined in a prior cell (eGgbxTZESJVs)
# or should be explicitly passed to functions that need it if not globally available.
# For this fix, we assume IMAGE_SIZE, NOISE_TYPES, DENOISING_METHODS, SUPPORTED_FORMATS,
# INPUT_DATASET_DIR, OUTPUT_DIR, RESULTS_DIR are all defined in a previous cell (e.g., eGgbxTZESJVs)
# and are accessible in the global scope.

def create_directories(dirs):
    """Creates directories if they do not exist."""
    for dir_path in dirs:
        os.makedirs(dir_path, exist_ok=True)
        print(f"Ensured directory exists: {dir_path}")

def read_and_preprocess_image(image_path, target_size=IMAGE_SIZE):
    """
    Reads an image, converts it to grayscale, resizes it, and normalizes pixel values.
    Args:
        image_path (str): Path to the image file.
        target_size (tuple): Desired (width, height) for the resized image.
    Returns:
        np.ndarray: Preprocessed image as a float64 NumPy array with values [0, 1].
                    Returns None if the image cannot be read.
    """
    try:
        # Read image in grayscale
        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f"Warning: Could not read image {image_path}. Skipping.")
            return None

        # Resize image
        img = cv2.resize(img, target_size, interpolation=cv2.INTER_AREA)

        # Normalize pixel values to [0, 1]
        img = img.astype(np.float64) / 255.0

        return img
    except Exception as e:
        print(f"Error processing image {image_path}: {e}. Skipping.")
        return None

def save_image(image_array, output_path):
    """
    Saves an image to the specified path.
    Args:
        image_array (np.ndarray): Image data (float64, [0,1]) to save.
        output_path (str): Full path including filename and extension to save the image.
    """
    try:
        # Convert back to uint8 [0, 255] before saving with OpenCV
        img_to_save = (image_array * 255).astype(np.uint8)
        cv2.imwrite(output_path, img_to_save)
    except Exception as e:
        print(f"Error saving image to {output_path}: {e}")

def calculate_metrics(original_img, noisy_img, denoised_img):
    """
    Calculates image quality metrics (Mean, Median, Std Dev, MSE, PSNR, SSIM).
    Args:
        original_img (np.ndarray): Original image (float64, [0, 1]).
        noisy_img (np.ndarray): Noisy image (float64, [0, 1]).
        denoised_img (np.ndarray): Denoised image (float64, [0, 1]).
    Returns:
        dict: A dictionary containing calculated metrics.
    """
    metrics = {}
    # Convert images to 8-bit for SSIM if they are float64, as SSIM expects uint8 by default
    # or float in a specific range and data_range specified.

    # For float [0, 1] images, set data_range=1 for SSIM and PSNR.

    # Metrics for Original Image (e.g., characteristics)
    metrics['Original_Mean'] = np.mean(original_img)
    metrics['Original_Median'] = np.median(original_img)
    metrics['Original_StdDev'] = np.std(original_img)

    # MSE: Mean Squared Error between two images
    metrics['MSE_Noisy_vs_Original'] = mean_squared_error(original_img, noisy_img)
    metrics['MSE_Denoised_vs_Original'] = mean_squared_error(original_img, denoised_img)

    # PSNR: Peak Signal-to-Noise Ratio
    # PSNR is usually calculated for image pairs with a maximum possible pixel value (e.g., 255 for uint8, 1 for float [0,1]).
    metrics['PSNR_Noisy_vs_Original'] = peak_signal_noise_ratio(original_img, noisy_img, data_range=1)
    metrics['PSNR_Denoised_vs_Original'] = peak_signal_noise_ratio(original_img, denoised_img, data_range=1)

    # SSIM: Structural Similarity Index
    # Requires data_range=1 for float images [0,1]
    metrics['SSIM_Noisy_vs_Original'] = structural_similarity(original_img, noisy_img, data_range=1)
    metrics['SSIM_Denoised_vs_Original'] = structural_similarity(original_img, denoised_img, data_range=1)

    return metrics

def process_dataset(input_root_dir, output_root_dir, image_size, noise_types, denoising_methods, supported_formats):
    """
    Processes the entire dataset: applies noise, denoises, calculates metrics, and saves results.
    Args:
        input_root_dir (str): Root directory of the input dataset.
        output_root_dir (str): Root directory for all outputs (noisy, denoised, results).
        image_size (tuple): Target size for image resizing (width, height).
        noise_types (dict): Dictionary of noise types and their functions.
        denoising_methods (dict): Dictionary of denoising methods and their functions.
        supported_formats (tuple): Tuple of supported image file extensions.
    Returns:
        pd.DataFrame: A DataFrame containing all calculated metrics and paths.
    """
    results_list = []

    # Setup output directories relative to output_root_dir
    noisy_output_dir = os.path.join(output_root_dir, 'noisy')
    denoised_output_dir = os.path.join(output_root_dir, 'denoised')

    # Ensure these specific output directories exist
    create_directories([noisy_output_dir, denoised_output_dir])

    print(f"Starting dataset processing from: {input_root_dir}")

    for class_folder in os.listdir(input_root_dir):
        class_path = os.path.join(input_root_dir, class_folder)
        if not os.path.isdir(class_path):
            continue

        print(f"Processing class: {class_folder}")

        for image_name in os.listdir(class_path):
            if not image_name.lower().endswith(supported_formats):
                print(f"Skipping unsupported file: {image_name}")
                continue

            original_image_path = os.path.join(class_path, image_name)
            base_name = os.path.splitext(image_name)[0]

            original_img = read_and_preprocess_image(original_image_path, image_size)
            if original_img is None:
                continue

            for noise_name, noise_func in noise_types.items():
                print(f"  Applying {noise_name} noise to {image_name}")
                noisy_img = noise_func(original_img)

                # Save noisy image
                noisy_image_filename = f"{base_name}_{noise_name}_noisy.png"
                noisy_image_path = os.path.join(noisy_output_dir, noisy_image_filename)
                save_image(noisy_img, noisy_image_path)

                for method_name, denoise_func in denoising_methods.items():
                    print(f"    Denoising with {method_name}")
                    denoised_img = denoise_func(noisy_img)

                    # Save denoised image
                    denoised_image_filename = f"{base_name}_{noise_name}_{method_name}_denoised.png"
                    denoised_image_path = os.path.join(denoised_output_dir, denoised_image_filename)
                    save_image(denoised_img, denoised_image_path)

                    # Calculate metrics
                    metrics = calculate_metrics(original_img, noisy_img, denoised_img)

                    row = {
                        'Image Name': image_name,
                        'Class': class_folder,
                        'Noise Type': noise_name,
                        'Denoising Method': method_name,
                        **metrics,
                        'Noisy Image Path': noisy_image_path,
                        'Denoised Image Path': denoised_image_path
                    }
                    results_list.append(row)

    print("Dataset processing complete.")
    return pd.DataFrame(results_list)

# Run the main processing function again to include new noise/denoising methods
print("--- Starting full dataset processing with updated methods ---")
all_results_df = process_dataset(
    input_root_dir=INPUT_DATASET_DIR,
    output_root_dir=OUTPUT_DIR,
    image_size=IMAGE_SIZE,
    noise_types=NOISE_TYPES,
    denoising_methods=DENOISING_METHODS,
    supported_formats=SUPPORTED_FORMATS
)

# Save the results to CSV and Excel
csv_output_path = os.path.join(RESULTS_DIR, 'final_results.csv')
excel_output_path = os.path.join(RESULTS_DIR, 'final_results.xlsx')

all_results_df.to_csv(csv_output_path, index=False)
all_results_df.to_excel(excel_output_path, index=False)

print(f"Results saved to: {csv_output_path}")
print(f"Results saved to: {excel_output_path}")
print("--- Dataset processing and results saving complete ---")

# Display updated sample images
print("Displaying updated sample images...")

if not all_results_df.empty:
    sample_rows = all_results_df.drop_duplicates(subset=['Image Name', 'Class', 'Noise Type', 'Denoising Method']).head(3)

    for index, row in sample_rows.iterrows():
        original_img_path = os.path.join(INPUT_DATASET_DIR, row['Class'], row['Image Name'])
        original_img = read_and_preprocess_image(original_img_path, IMAGE_SIZE)

        noisy_img = read_and_preprocess_image(row['Noisy Image Path'], IMAGE_SIZE)
        denoised_img = read_and_preprocess_image(row['Denoised Image Path'], IMAGE_SIZE)

        if original_img is not None and noisy_img is not None and denoised_img is not None:
            title_suffix = f"\nNoise: {row['Noise Type']}, Denoising: {row['Denoising Method']}"
            display_sample_images(original_img, noisy_img, denoised_img, title_suffix)
else:
    print("No results to display. Please check if the dataset processing was successful.")

print("Sample image visualization complete.")

# Generate updated comparison plots
print("Generating updated comparison plots...")

create_directories([RESULTS_DIR])

if not all_results_df.empty:
    psnr_plot_path = os.path.join(RESULTS_DIR, 'psnr_comparison.png')
    plot_metrics_comparison(all_results_df, 'PSNR_Denoised_vs_Original',
                            'Average PSNR Comparison (Denoised vs Original)', 'Average PSNR (dB)', psnr_plot_path)

    ssim_plot_path = os.path.join(RESULTS_DIR, 'ssim_comparison.png')
    plot_metrics_comparison(all_results_df, 'SSIM_Denoised_vs_Original',
                            'Average SSIM Comparison (Denoised vs Original)', 'Average SSIM', ssim_plot_path)
else:
    print("No results to plot. Please ensure the DataFrame 'all_results_df' is populated.")

print("Comparison plots generated and saved.")

# Generate updated summary statistics
print("Generating updated summary statistics...")

if not all_results_df.empty:
    summary_metrics = ['PSNR_Denoised_vs_Original', 'SSIM_Denoised_vs_Original', 'MSE_Denoised_vs_Original']
    summary_df = all_results_df.groupby(['Noise Type', 'Denoising Method'])[summary_metrics].mean().reset_index()

    summary_df_sorted = summary_df.sort_values(by=['Noise Type', 'PSNR_Denoised_vs_Original'], ascending=[True, False])

    print("\n--- Summary Statistics (Average Metrics) ---")
    print(summary_df_sorted.to_string())

    summary_csv_path = os.path.join(RESULTS_DIR, 'summary_statistics.csv')
    summary_excel_path = os.path.join(RESULTS_DIR, 'summary_statistics.xlsx')

    summary_df_sorted.to_csv(summary_csv_path, index=False)
    summary_df_sorted.to_excel(excel_output_path, index=False) # Fix: Changed to summary_excel_path

    print(f"\nSummary statistics saved to: {summary_csv_path}")
    print(f"Summary statistics saved to: {summary_excel_path}")
else:
    print("No results to generate summary statistics. Please ensure the DataFrame 'all_results_df' is populated.")

print("Summary statistics generation complete.")

"""First, we need to install all the necessary Python libraries that will be used throughout this project. These include `opencv-python` for image processing, `scikit-image` for image quality metrics, `scipy` for scientific computing, `pandas` for data manipulation, `openpyxl` for Excel output, and `kaggle` for dataset download."""

# Install necessary libraries
!pip install opencv-python scikit-image scipy pandas openpyxl kaggle

"""### Image Preprocessing Functions"""

def read_and_preprocess_image(image_path, target_size=IMAGE_SIZE):
    """
    Reads an image, converts it to grayscale, resizes it, and normalizes pixel values.
    Args:
        image_path (str): Path to the image file.
        target_size (tuple): Desired (width, height) for the resized image.
    Returns:
        np.ndarray: Preprocessed image as a float64 NumPy array with values [0, 1].
                    Returns None if the image cannot be read.
    """
    try:
        # Read image in grayscale
        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            print(f"Warning: Could not read image {image_path}. Skipping.")
            return None

        # Resize image
        img = cv2.resize(img, target_size, interpolation=cv2.INTER_AREA)

        # Normalize pixel values to [0, 1]
        img = img.astype(np.float64) / 255.0

        return img
    except Exception as e:
        print(f"Error processing image {image_path}: {e}. Skipping.")
        return None

def save_image(image_array, output_path):
    """
    Saves an image to the specified path.
    Args:
        image_array (np.ndarray): Image data (float64, [0,1]) to save.
        output_path (str): Full path including filename and extension to save the image.
    """
    try:
        # Convert back to uint8 [0, 255] before saving with OpenCV
        img_to_save = (image_array * 255).astype(np.uint8)
        cv2.imwrite(output_path, img_to_save)
    except Exception as e:
        print(f"Error saving image to {output_path}: {e}")

print("Image preprocessing and saving functions defined.")

"""### Noise Addition and Denoising Functions"""

def add_noise(image, noise_type):
    """
    Applies specified noise to an image.
    Args:
        image (np.ndarray): Original image (float64, [0, 1]).
        noise_type (str): Type of noise to apply ('gaussian', 's&p', 'speckle', 'poisson').
    Returns:
        np.ndarray: Noisy image (float64, [0, 1]).
    """
    if noise_type not in NOISE_TYPES:
        raise ValueError(f"Unsupported noise type: {noise_type}")

    # random_noise function returns image in range [0, 1] for float images
    noisy_image = NOISE_TYPES[noise_type](image)
    return noisy_image

def apply_denoising(noisy_image, method):
    """
    Applies a specified denoising method to a noisy image.
    Args:
        noisy_image (np.ndarray): Noisy image (float64, [0, 1]).
        method (str): Denoising method to apply ('median', 'gaussian', 'wiener', 'bilateral', 'non_local_means').
    Returns:
        np.ndarray: Denoised image (float64, [0, 1]).
    """
    if method not in DENOISING_METHODS:
        raise ValueError(f"Unsupported denoising method: {method}")

    denoised_image = DENOISING_METHODS[method](noisy_image)
    # Ensure output is clamped to [0, 1] as some filters might slightly exceed this range
    return np.clip(denoised_image, 0, 1)

print("Noise addition and denoising functions defined.")

"""### Image Quality Metrics Calculation"""

def calculate_metrics(original_img, noisy_img, denoised_img):
    """
    Calculates image quality metrics (Mean, Median, Std Dev, MSE, PSNR, SSIM).
    Args:
        original_img (np.ndarray): Original image (float64, [0, 1]).
        noisy_img (np.ndarray): Noisy image (float64, [0, 1]).
        denoised_img (np.ndarray): Denoised image (float64, [0, 1]).
    Returns:
        dict: A dictionary containing calculated metrics.
    """
    metrics = {}
    # Convert images to 8-bit for SSIM if they are float64, as SSIM expects uint8 by default
    # or float in a specific range and data_range specified.

    # For float [0, 1] images, set data_range=1 for SSIM and PSNR.

    # Metrics for Original Image (e.g., characteristics)
    metrics['Original_Mean'] = np.mean(original_img)
    metrics['Original_Median'] = np.median(original_img)
    metrics['Original_StdDev'] = np.std(original_img)

    # MSE: Mean Squared Error between two images
    metrics['MSE_Noisy_vs_Original'] = mean_squared_error(original_img, noisy_img)
    metrics['MSE_Denoised_vs_Original'] = mean_squared_error(original_img, denoised_img)

    # PSNR: Peak Signal-to-Noise Ratio
    # PSNR is usually calculated for image pairs with a maximum possible pixel value (e.g., 255 for uint8, 1 for float [0,1]).
    metrics['PSNR_Noisy_vs_Original'] = peak_signal_noise_ratio(original_img, noisy_img, data_range=1)
    metrics['PSNR_Denoised_vs_Original'] = peak_signal_noise_ratio(original_img, denoised_img, data_range=1)

    # SSIM: Structural Similarity Index
    # Requires data_range=1 for float images [0,1]
    metrics['SSIM_Noisy_vs_Original'] = structural_similarity(original_img, noisy_img, data_range=1)
    metrics['SSIM_Denoised_vs_Original'] = structural_similarity(original_img, denoised_img, data_range=1)

    return metrics

print("Image quality metrics calculation function defined.")

"""### Main Dataset Processing Pipeline"""

def process_dataset(input_root_dir, output_root_dir, image_size, noise_types, denoising_methods, supported_formats):
    """
    Processes the entire dataset: applies noise, denoises, calculates metrics, and saves results.
    Args:
        input_root_dir (str): Root directory of the input dataset.
        output_root_dir (str): Root directory for all outputs (noisy, denoised, results).
        image_size (tuple): Target size for image resizing (width, height).
        noise_types (dict): Dictionary of noise types and their functions.
        denoising_methods (dict): Dictionary of denoising methods and their functions.
        supported_formats (tuple): Tuple of supported image file extensions.
    Returns:
        pd.DataFrame: A DataFrame containing all calculated metrics and paths.
    """
    results_list = []

    # Setup output directories relative to output_root_dir
    noisy_output_dir = os.path.join(output_root_dir, 'noisy')
    denoised_output_dir = os.path.join(output_root_dir, 'denoised')

    # Ensure these specific output directories exist
    create_directories([noisy_output_dir, denoised_output_dir])

    print(f"Starting dataset processing from: {input_root_dir}")

    for class_folder in os.listdir(input_root_dir):
        class_path = os.path.join(input_root_dir, class_folder)
        if not os.path.isdir(class_path):
            continue

        print(f"Processing class: {class_folder}")

        for image_name in os.listdir(class_path):
            if not image_name.lower().endswith(supported_formats):
                print(f"Skipping unsupported file: {image_name}")
                continue

            original_image_path = os.path.join(class_path, image_name)
            base_name = os.path.splitext(image_name)[0]

            original_img = read_and_preprocess_image(original_image_path, image_size)
            if original_img is None:
                continue

            for noise_name, noise_func in noise_types.items():
                print(f"  Applying {noise_name} noise to {image_name}")
                noisy_img = noise_func(original_img)

                # Save noisy image
                noisy_image_filename = f"{base_name}_{noise_name}_noisy.png"
                noisy_image_path = os.path.join(noisy_output_dir, noisy_image_filename)
                save_image(noisy_img, noisy_image_path)

                for method_name, denoise_func in denoising_methods.items():
                    print(f"    Denoising with {method_name}")
                    denoised_img = denoise_func(noisy_img)

                    # Save denoised image
                    denoised_image_filename = f"{base_name}_{noise_name}_{method_name}_denoised.png"
                    denoised_image_path = os.path.join(denoised_output_dir, denoised_image_filename)
                    save_image(denoised_img, denoised_image_path)

                    # Calculate metrics
                    metrics = calculate_metrics(original_img, noisy_img, denoised_img)

                    row = {
                        'Image Name': image_name,
                        'Class': class_folder,
                        'Noise Type': noise_name,
                        'Denoising Method': method_name,
                        **metrics,
                        'Noisy Image Path': noisy_image_path,
                        'Denoised Image Path': denoised_image_path
                    }
                    results_list.append(row)

    print("Dataset processing complete.")
    return pd.DataFrame(results_list)

print("Main dataset processing function defined.")

"""### Visualization Functions"""

import matplotlib.pyplot as plt

def display_sample_images(original_img, noisy_img, denoised_img, title_suffix=""):
    """
    Displays original, noisy, and denoised images side-by-side.
    Args:
        original_img (np.ndarray): Original image (float64, [0, 1]).
        noisy_img (np.ndarray): Noisy image (float64, [0, 1]).
        denoised_img (np.ndarray): Denoised image (float64, [0, 1]).
        title_suffix (str): Additional text for the plot title.
    """
    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    axes[0].imshow(original_img, cmap='gray')
    axes[0].set_title('Original Image')
    axes[0].axis('off')

    axes[1].imshow(noisy_img, cmap='gray')
    axes[1].set_title(f'Noisy Image {title_suffix}')
    axes[1].axis('off')

    axes[2].imshow(denoised_img, cmap='gray')
    axes[2].set_title(f'Denoised Image {title_suffix}')
    axes[2].axis('off')

    plt.tight_layout()
    plt.show()

def plot_metrics_comparison(df, metric_name, title, y_label, save_path=None):
    """
    Generates comparison plots for specified metrics (e.g., PSNR, SSIM).
    Args:
        df (pd.DataFrame): DataFrame containing the results.
        metric_name (str): Name of the metric column to plot (e.g., 'PSNR_Denoised_vs_Original').
        title (str): Title of the plot.
        y_label (str): Label for the Y-axis.
        save_path (str, optional): Path to save the plot. If None, plot is not saved.
    """
    plt.figure(figsize=(12, 6))

    # Group by 'Noise Type' and 'Denoising Method' and calculate the mean of the metric
    plot_data = df.groupby(['Noise Type', 'Denoising Method'])[metric_name].mean().unstack()

    plot_data.plot(kind='bar', figsize=(15, 7))
    plt.title(title)
    plt.xlabel('Noise Type')
    plt.ylabel(y_label)
    plt.xticks(rotation=45, ha='right')
    plt.legend(title='Denoising Method', bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.tight_layout()

    if save_path:
        plt.savefig(save_path)
        print(f"Plot saved to: {save_path}")
    plt.show()

print("Visualization functions defined.")

"""## Execute the Pipeline

Now, we will execute the entire processing pipeline. This step will take some time depending on the size of the dataset and the number of noise/denoising combinations.
"""

# # Run the main processing function
# print("--- Starting full dataset processing ---")
# all_results_df = process_dataset(
#     input_root_dir=INPUT_DATASET_DIR,
#     output_root_dir=OUTPUT_DIR,
#     image_size=IMAGE_SIZE,
#     noise_types=NOISE_TYPES,
#     denoising_methods=DENOISING_METHODS, # Use the globally defined DENOISING_METHODS
#     supported_formats=SUPPORTED_FORMATS
# )

# # Save the results to CSV and Excel
# csv_output_path = os.path.join(RESULTS_DIR, 'final_results.csv')
# excel_output_path = os.path.join(RESULTS_DIR, 'final_results.xlsx')

# all_results_df.to_csv(csv_output_path, index=False)
# all_results_df.to_excel(excel_output_path, index=False)

# print(f"Results saved to: {csv_output_path}")
# print(f"Results saved to: {excel_output_path}")
# print("--- Dataset processing and results saving complete ---")

# Select a few samples for visualization
# For demonstration, we'll pick the first few entries in the results DataFrame

print("Displaying sample images...")

# Ensure there are results to display
if not all_results_df.empty:
    # Get unique combinations of Image Name, Class, Noise Type, Denoising Method for samples
    sample_rows = all_results_df.drop_duplicates(subset=['Image Name', 'Class', 'Noise Type', 'Denoising Method']).head(3)

    for index, row in sample_rows.iterrows():
        original_img_path = os.path.join(INPUT_DATASET_DIR, row['Class'], row['Image Name'])
        # Read the original image from the input dataset directory
        original_img = read_and_preprocess_image(original_img_path, IMAGE_SIZE)

        # Read noisy and denoised images from their respective output paths
        # These are already saved as PNGs, so we can directly read them back.
        noisy_img = read_and_preprocess_image(row['Noisy Image Path'], IMAGE_SIZE) # Read as preprocessed float
        denoised_img = read_and_preprocess_image(row['Denoised Image Path'], IMAGE_SIZE) # Read as preprocessed float

        if original_img is not None and noisy_img is not None and denoised_img is not None:
            title_suffix = f"\nNoise: {row['Noise Type']}, Denoising: {row['Denoising Method']}"
            display_sample_images(original_img, noisy_img, denoised_img, title_suffix)
else:
    print("No results to display. Please check if the dataset processing was successful.")

print("Sample image visualization complete.")

"""## Generate Comparison Plots

Quantitative analysis of denoising performance is crucial. We will generate bar plots to compare PSNR and SSIM values across different noise types and denoising methods. These plots will be saved to the results directory.
"""

print("Generating comparison plots...")

# Ensure the results directory exists for saving plots
create_directories([RESULTS_DIR])

if not all_results_df.empty:
    # Plot PSNR
    psnr_plot_path = os.path.join(RESULTS_DIR, 'psnr_comparison.png')
    plot_metrics_comparison(all_results_df, 'PSNR_Denoised_vs_Original',
                            'Average PSNR Comparison (Denoised vs Original)', 'Average PSNR (dB)', psnr_plot_path)

    # Plot SSIM
    ssim_plot_path = os.path.join(RESULTS_DIR, 'ssim_comparison.png')
    plot_metrics_comparison(all_results_df, 'SSIM_Denoised_vs_Original',
                            'Average SSIM Comparison (Denoised vs Original)', 'Average SSIM', ssim_plot_path)
else:
    print("No results to plot. Please ensure the DataFrame 'all_results_df' is populated.")

print("Comparison plots generated and saved.")

"""## Generate Summary Statistics

To get an overview of the performance, we will generate summary statistics for all metrics, grouped by noise type and denoising method. This table will also be saved as a CSV and Excel file.
"""

print("Generating summary statistics...")

if not all_results_df.empty:
    # Group by Noise Type and Denoising Method and calculate mean for relevant metrics
    summary_metrics = ['PSNR_Denoised_vs_Original', 'SSIM_Denoised_vs_Original', 'MSE_Denoised_vs_Original']
    summary_df = all_results_df.groupby(['Noise Type', 'Denoising Method'])[summary_metrics].mean().reset_index()

    # Optionally, sort by a key metric to easily identify best performers
    summary_df_sorted = summary_df.sort_values(by=['Noise Type', 'PSNR_Denoised_vs_Original'], ascending=[True, False])

    print("\n--- Summary Statistics (Average Metrics) ---")
    print(summary_df_sorted.to_string())

    # Save summary statistics to CSV and Excel
    summary_csv_path = os.path.join(RESULTS_DIR, 'summary_statistics.csv')
    summary_excel_path = os.path.join(RESULTS_DIR, 'summary_statistics.xlsx')

    summary_df_sorted.to_csv(summary_csv_path, index=False)
    summary_df_sorted.to_excel(summary_excel_path, index=False)

    print(f"\nSummary statistics saved to: {summary_csv_path}")
    print(f"Summary statistics saved to: {summary_excel_path}")
else:
    print("No results to generate summary statistics. Please ensure the DataFrame 'all_results_df' is populated.")

print("Summary statistics generation complete.")

"""## Project Conclusion and Future Work

This Google Colab project successfully implements a comprehensive pipeline for mammography-based breast cancer image preprocessing and comparative denoising analysis. We have:

*   **Set up the environment:** Installed necessary libraries and mounted Google Drive.
*   **Acquired and prepared data:** Downloaded and unzipped the Kaggle Breast Cancer Mammograms dataset.
*   **Implemented core functionalities:** Functions for reading, preprocessing, adding various noise types (Gaussian, Salt & Pepper, Speckle, Poisson), and applying multiple denoising techniques (Median, Gaussian, Wiener, Bilateral, Non-Local Means).
*   **Calculated and stored metrics:** Generated Mean, Median, Std Dev, MSE, PSNR, and SSIM for all processed images.
*   **Organized outputs:** Saved noisy and denoised images, and results tables in a structured `output/` directory.
*   **Visualized results:** Displayed sample images and generated comparative plots for PSNR and SSIM.
*   **Provided summary statistics:** Created summary tables for average metric performance.

The generated CSV and Excel files, along with the plots, provide research-ready outputs for analyzing the effectiveness of different denoising methods on mammogram images corrupted by various noise types.

### Next Steps and Future Extensions:

As outlined in the project description, this pipeline is designed for future extensibility:

1.  **CNN Classification:** The preprocessed (denoised) images can be directly fed into Convolutional Neural Networks for breast cancer classification.
2.  **Advanced Architectures:** The framework can be extended to evaluate denoised images with state-of-the-art models like ResNet, EfficientNet, or Vision Transformers.
3.  **Denoising Impact Analysis:** A critical future step would be to perform a 'before-vs-after denoising' classification accuracy comparison to quantify the benefits of denoising on diagnostic performance.
4.  **Parameter Tuning:** Further research could involve hyperparameter tuning for each denoising method and noise type to optimize performance.
5.  **Domain-Specific Denoising:** Explore more advanced, mammography-specific denoising algorithms.

This project serves as a robust foundation for deeper research into improving breast cancer detection through image preprocessing and denoising techniques.
"""